# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:slug

# Setup
title:            Zelly Snyder
tagline:          'programming tutorials & essays'
description:      'essays & tutorials on programming, investing, health'
url:              https://blog.zellysnyder.com
baseurl:          /
year_created: 2014

author:
  name:           'Zelly Snyder'
  #url:            https://twitter.com/mdo

paginate:         10

plugins:
  - jekyll-paginate
  - jekyll-org-to-html

version: 0.0.1

collections:
  software:
    output: true
    label: Software
  tutorials:
    output: true
    label: Programming Tutorials
